#!/bin/bash
set -e

HERE="$(dirname "$(readlink -f "$0")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"

mkdir -p "${HOME}/.parsec"

exec "${HERE}/usr/bin/parsecd" "$@"